import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

import Navbars from './components/next-ui/Navbar'
import Footer from './components/Footer/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-full px-20 flex flex-1 flex-col items-start justify-center">
        <Navbars />
      <Providers>
     
          {children}
        <Footer />
        {/* </div> */}
        </Providers>
      </body>
    </html>
  )
}
